{{- $fullName := include "decidim-helm.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "decidim-helm.fullname" . }}
spec:
  ttlSecondsAfterFinished: {{ .Values.migrateJob.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
        - name: decidim-sen-migration-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{ .Values.migrateJob.command }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" $fullName "config" }}
            - secretRef:
                name: {{ printf "%s-%s" $fullName "secrets" }}
      restartPolicy: Never
