{{- $fullName := include "decidim-helm.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "decidim-helm.sdqFullname" . }}
  labels:
    {{- include "decidim-helm.sdqLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "decidim-helm.sdqFullname" . }}
  {{- if not .Values.hpa.sidekiq.enabled }}
  replicas: {{ .Values.deployment.sidekiq.replicasCount }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.sidekiq.spec.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "decidim-helm.sdqSelectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "decidim-helm.sdqFullname" . }}
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: {{ .Values.deployment.sidekiq.spec.termination.gracePeriodSeconds }}
      containers:
        - name: {{ include "decidim-helm.sdqFullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.deployment.sidekiq.spec.containers.resources | nindent 12 }}
          command: [ "sidekiq", "-C", "config/sidekiq.yml" ]
          ports:
            - containerPort: 7433
          {{ if .Values.deployment.sidekiq.spec.containers.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /sidekiq_alive
              port: 7433
            initialDelaySeconds: {{ .Values.deployment.sidekiq.spec.containers.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deployment.sidekiq.spec.containers.livenessProbe.timeoutSeconds }}
          {{ end }}
          {{ if .Values.deployment.sidekiq.spec.containers.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /sidekiq_alive
              port: 7433
            initialDelaySeconds: {{ .Values.deployment.sidekiq.spec.containers.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deployment.sidekiq.spec.containers.readinessProbe.timeoutSeconds }}
          {{ end }}
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: [ './sidekiq_quiet.sh' ]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" $fullName "config" }}
            - secretRef:
                name: {{ printf "%s-%s" $fullName "secrets" }}