{{- $fullName := include "decidim-helm.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{printf "%s-%s" $fullName "secrets" }}
type: Opaque
data:
  {{- if .Values.databases.postgresql.externalPostgresDabatase }}
  DATABASE_URL: {{ .Values.database_url | b64enc }}
  {{- end }}
